#Task-1(Array creation)

In [4]:
import numpy as np

In [6]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
b=np.full((3,3),7)
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


#Task-2(Array Operations)

In [10]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

d=np.array([[10,11,12],[13,14,15],[16,17,18]])

add= np.add(c,d)
multiply=np.multiply(c,d)
print("Addition:",add)
print("Multiplication:",multiply)


Addition: [[11 13 15]
 [17 19 21]
 [23 25 27]]
Multiplication: [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [17]:
a= np.random.randint(10,50,16)
a=a.reshape(4,4)
print("4 x 4 matrix:")
print(a)
print("Maximum value:",np.max(a))
print("Minimum value:",np.min(a))

4 x 4 matrix:
[[49 21 18 16]
 [26 28 46 32]
 [48 33 43 20]
 [48 37 18 46]]
Maximum value: 49
Minimum value: 16


#Task-3(Indexing and slicing)

In [22]:
array = np.arange(1, 26).reshape(5, 5)

print("Original 5x5 array:")
print(array)

middle_sub_array = array[1:4, 1:4]

print("\nMiddle 3x3 sub-array:")
print(middle_sub_array)


Original 5x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Middle 3x3 sub-array:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [29]:
a= np.random.randint(10,50,16)
a=a.reshape(4,4)
print("Old array:\n",a)
new_a= a[0,:]=0    #set first row to zero (all elements)
print("New array:\n",a)

Old array:
 [[11 49 42 11]
 [14 43 34 22]
 [21 16 17 24]
 [14 11 14 19]]
New array:
 [[ 0  0  0  0]
 [14 43 34 22]
 [21 16 17 24]
 [14 11 14 19]]


#Task-4(Mathematical operations)

In [31]:
random_array=np.random.randint(1000,size=(10,10))
print(random_array)
mean=np.mean(random_array)
print("Mean:",mean)
median=np.median(random_array)
print("Median:",median)
std=np.std(random_array)
print("Standard Deviation:",std)

[[ 30 297 598 105 401 272 126 265 411 948]
 [619 120 716 296 389 273  98 518 598 373]
 [415 971 637 476 799 250 182 366 656 386]
 [884 104 430 271 463 330 939 710 166 445]
 [589 331 841 326  32 288 522 241 290 205]
 [569 405 551 994 305 536 299 433 177 153]
 [319 107 683 439 923 742 889 241 820 534]
 [284 988 940 189 837 775 913  41 132 850]
 [827 501 246 439  98 284 119 548 136 349]
 [704 962 209 947 675 501 972 473 447 659]]
Mean: 471.62
Median: 431.5
Standard Deviation: 274.25272213781216


In [33]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
print("Array1:\n",array1)
print("Array2:\n",array2)
result=np.dot(array1,array2)
print("Dot product of array1 and array2:\n",result)

Array1:
 [1 2 3 4]
Array2:
 [5 6 7 8]
Dot product of array1 and array2:
 70


#Task-5(Broadcasting)

In [34]:
array_2d = np.zeros((5, 5))

array_1d = np.array([1, 2, 3, 4, 5])

print("Original 5x5 array of zeros:")
print(array_2d)

print("\n1D array:")
print(array_1d)

# Adding the 1D array to each row of the 2D array using broadcasting
array_2d += array_1d

print("\n5x5 array after adding the 1D array to each row:")
print(array_2d)


Original 5x5 array of zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

1D array:
[1 2 3 4 5]

5x5 array after adding the 1D array to each row:
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [36]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

scaler_value=2
print("Original array:")
print(array)
result= array-scaler_value
print("Result of subtraction:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result of subtraction:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


#Task-6(Aggregations)

In [37]:
a= np.random.randint(1,10,36)
a=a.reshape(6,6)
print("6 x 6 matrix:")
print(a)
print("Sum of all elements:",np.sum(a))

6 x 6 matrix:
[[5 5 7 8 7 9]
 [7 5 6 3 8 1]
 [9 2 1 8 2 3]
 [8 9 3 2 5 6]
 [9 8 2 3 8 6]
 [7 1 7 2 7 9]]
Sum of all elements: 198


In [42]:
x=np.random.randint(1,100,50)
print("50 random values:")
print(x)
print("Maximum value:",np.max(x))
print("index of maximum value:",np.argmax(x))

50 random values:
[61 73 80 61 10 92 35 21 63  7 30 77 25  9 71 64 31 33 32 69 31 91 49 14
 17 21 23 92 88 31 45 10 47 10 17 51 53 81  9 57  4 46 29 82 89 60 10 94
 82 26]
Maximum value: 94
index of maximum value: 47


#Task-7(Reshaping and Flattening)

In [44]:
a= np.random.randint(1,10,12)
print("1D array:")
print(a)
b=a.reshape(3,4)
print("2D array:")
print(b)

1D array:
[5 6 4 7 3 9 1 1 7 2 2 5]
2D array:
[[5 6 4 7]
 [3 9 1 1]
 [7 2 2 5]]


In [48]:
b=np.array([[5, 6, 4, 7],
            [3, 9, 1, 1],
            [7, 2, 2, 5]])
print("2D array:")
print(b)
b=a.flatten()
print("Flattened array:")
print(b)

2D array:
[[5 6 4 7]
 [3 9 1 1]
 [7 2 2 5]]
Flattened array:
[5 6 4 7 3 9 1 1 7 2 2 5]


#Task-8(Linear Algebra)

In [49]:
A = np.array([[2, 3],
              [1, 2]])

b = np.array([8, 5])
solution = np.linalg.solve(A, b)

print("Solution of the system of linear equations:")
print(solution)


Solution of the system of linear equations:
[1. 2.]


In [50]:
matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

print("Original 3x3 matrix:")
print(matrix)

det = np.linalg.det(matrix)

if det != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is not invertible (determinant is zero).")


Original 3x3 matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


#Task-9(Statistical Analysis)

In [52]:
random_array=np.random.randint(10000,size=(100,100))
print(random_array)

correlation_coefficient = np.corrcoef(random_array)

print("\nCorrelation coefficient matrix:")
print(correlation_coefficient)

[[4691 2424 1040 ... 8251 2176 7490]
 [ 298 1607 9396 ... 5173  941 5124]
 [1396 8104 1040 ...  470 6549  509]
 ...
 [3988  286 1163 ... 3288 6879 4236]
 [6798   27 9827 ... 7823 7288 5320]
 [7236 6682 8207 ... 4528 5778 4928]]

Correlation coefficient matrix:
[[ 1.          0.05541437  0.03424936 ... -0.02580252  0.06849302
  -0.12543764]
 [ 0.05541437  1.          0.01262934 ...  0.01924666  0.04765806
  -0.27463141]
 [ 0.03424936  0.01262934  1.         ...  0.09582525 -0.01578762
  -0.01974293]
 ...
 [-0.02580252  0.01924666  0.09582525 ...  1.         -0.05935006
  -0.08127749]
 [ 0.06849302  0.04765806 -0.01578762 ... -0.05935006  1.
  -0.21273791]
 [-0.12543764 -0.27463141 -0.01974293 ... -0.08127749 -0.21273791
   1.        ]]


In [57]:
array = np.random.randint(20, size=20)

print("1D array:")
print(array)

cumulative_sum= np.cumsum(array)

print("\nCumulative sum of the array:")
print(cumulative_sum)

1D array:
[ 2  4 13  6 11  2 18 14  0  9 11 18 16  3  5 11  3 14 18 14]

Cumulative sum of the array:
[  2   6  19  25  36  38  56  70  70  79  90 108 124 127 132 143 146 160
 178 192]


#Task-10(Advanced Indexing)

##**Note:- **Important Topic for future Machine Learning

In [58]:
matrix = np.random.randint(1, 10, size=(4, 4))

print("Original 4x4 matrix:")
print(matrix)

# Using boolean indexing to set all elements greater than 5 to -1
matrix[matrix > 5] = -1

print("\n4x4 matrix after setting elements greater than 5 to -1:")
print(matrix)


Original 4x4 matrix:
[[1 4 4 3]
 [5 9 8 4]
 [9 3 6 8]
 [4 6 1 3]]

4x4 matrix after setting elements greater than 5 to -1:
[[ 1  4  4  3]
 [ 5 -1 -1  4]
 [-1  3 -1 -1]
 [ 4 -1  1  3]]


In [67]:
import numpy as np


array = np.arange(1,26).reshape(5, 5)

print("Original 5x5 array:")
print(array)

# 1. Select rows where the sum of elements in the row is greater than 15
row_sums = array.sum(axis=1)
rows_to_select = np.where(row_sums > 15)[0]

# 2. Select columns where the mean of elements in the column is even
column_means = array.mean(axis=0)
columns_to_select = np.where(column_means % 2 == 0)[0]

# Extracting rows and columns based on conditions
selected_rows = array[rows_to_select, :]
selected_columns = array[:, columns_to_select]

print("\nRows where the sum of elements is greater than 15:")
print(selected_rows)

print("\nColumns where the mean of elements is even:")
print(selected_columns)


Original 5x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Rows where the sum of elements is greater than 15:
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Columns where the mean of elements is even:
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]
